### ISSUE TITLE
On windows with dotnet core SqlClient reports type 'SqlCommand' unavailable

### ISSUE THREAD

**Issue by AlexAtNet** [fsprojects/FSharp.Data.SqlClient#279] opened 2017-12-13 19:12 UTC
### Description

FSharp.Data.SqlClient on windows with dotnet core reports type 'SqlCommand' unavailable.

### Repro steps

I'm trying to use FSharp.Data.SqlClient on Windows

    c:\...> dotnet new console -lang f# -o test5
    c:\...> cd test5

Now add `<Import Project="fsc.props" />` to `test5.fsproj` and add `fsc.props` from `https://raw.githubusercontent.com/fsprojects/FSharp.TypeProviders.SDK/master/fsc.props`. Then

    c:\...\test5> dotnet add package FSharp.Data.SqlClient

And edit `Program.fs` as follows:

    
    open FSharp.Data
    open FSharp.Data.SqlClient

    [<Literal>]
    let connectionString = 
        @"Data Source=.\SQL14X64;Initial Catalog=test;User=sa;Password=***"

    [<EntryPoint>]
    let main argv =
        use cmd = new SqlCommandProvider<"
                SELECT 1
                " , connectionString>(connectionString)
        0

Trying to compile it:

    c:\...\test5> dotnet build

Have error:

     The type 'SqlCommand' is required here and is unavailable.
     You must add a reference to assembly 'System.Data.SqlClient, Version=0.0.0.0, ...

Ok, installing System.Data.SqlClient:

    c:\...\test5> dotnet add package System.Data.SqlClient

Have error:

    The type 'SqlCommand' is required here and is unavailable.
    You must add a reference to assembly 'System.Data.SqlClient, Version=4.2.0.1, ...

O-key, let install 4.2.0.1:

    c:\...\test5> dotnet remove package System.Data.SqlClient 
    c:\...\test5> dotnet add package System.Data.SqlClient --version 4.2.0.1
    c:\...\test5> dotnet build

Have error:

    The type 'SqlCommand' is required here and is unavailable.
    You must add a reference to assembly 'System.Data.SqlClient, Version=4.1.0.0, ...

Hm... Replace with 4.1.0.0:

    c:\...\test5> dotnet remove package System.Data.SqlClient 
    c:\...\test5> dotnet add package System.Data.SqlClient --version 4.1.0.0
    c:\...\test5> dotnet build

Have same error again:

    The type 'SqlCommand' is required here and is unavailable.
    You must add a reference to assembly 'System.Data.SqlClient, Version=4.1.0.0, ...

Cannot really move any further with it.

OS: Windows, .NET Core: 2.1.2

**Comment by dmitry-a-morozov** [comment] 2017-12-13 19:21
The project is not ported to NET Core.

**Comment by AndrewTakker** [comment] 2018-03-15 12:51
@dmitry-a-morozov have you a plan migrate it on NET Core?

**Comment by dmitry-a-morozov** [comment] 2018-03-15 16:45
No. Unfortunately as of now I don't participate in this project anymore. 
Company I work for uses Postgres so SQL Server is not priority.

**Comment by vasily-kirichenko** [comment] 2018-05-12 13:52
WIP https://github.com/fsprojects/FSharp.Data.SqlClient/pull/291, however, it's not going very well so far.

**Comment by vasily-kirichenko** [comment] 2018-05-12 13:55
I'm closing this as duplicate of https://github.com/fsprojects/FSharp.Data.SqlClient/issues/270

**Closed by vasily-kirichenko** 2018-05-12 13:55 UTC
