### ISSUE TITLE
Improve IDE (design-time) performance

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/FSharp.Data.SqlClient#343] opened 2019-05-29 17:35 UTC
I love SqlClient, but one thing that consistently gets me down is that as my DB file grows, things slow to a crawl in Visual Studio. We're talking about 5–10 seconds after each edit before Intellisense catches up, not to mention that editing in general is slow. When that happens, I effectively have to sacrifice productivity for type safety in using SqlClient.

Might there be some low-hanging fruit that could improve the design-time performance of SqlClient, or is this simply a fact of life with type providers?

(Note that SqlClient in my case is running against a localhost database, so there should be no network overhead.)

**Comment by charlesroddie** [comment] 2019-07-01 14:51
> is this simply a fact of life with type providers
> editing in general is slow
This is what SSDT is good for. Get better and faster intellisense when writing SQL, and then once it's finished let FSharp.Data.SqlClient manage the interface to F#. (With a 10s lag for a build.) Using FSharp.Data.SqlClient to help edit the SQL is not the best solution.

**Comment by cmeeren** [comment] 2019-07-01 16:42
Perhaps I wasn't clear enough; I was talking about F#/.NET intellisense, not SQL. (I'm using separate SQL files.) I'm not using SqlClient to help edit the SQL.

**Comment by smoothdeveloper** [comment] 2019-07-01 16:48
@cmeeren it is not clear to me if the issue is with F# tooling at large, or specific to (or let say significantly worsenned by) this SQL type provider, I've seen performance issues with tooling in different contexts.

If you have a very minimal sample using the provider that show poor performance, we can investigate a bit if the time is spent in the provider code or in the IDE itself, in which case it is worth reporting the case on dotnet/fsharp.

**Comment by cmeeren** [comment] 2019-07-01 19:05
> it is not clear to me if the issue is with F# tooling at large, or specific to (or let say significantly worsenned by) this SQL type provider

For files of equal length (say, 3000 lines), a file with lots of SqlClient usage (say, 50 functions using `SqlFile` and `SqlCommandProvider`) has terrible performance while a file with no SqlClient usage has acceptable performance.

I currently have no minimal sample. I will keep it in mind, but unfortunately I have my hands full for the time being.

**Comment by charlesroddie** [comment] 2020-09-18 09:28
As our queries have grown we are getting perf from FSharp.Data.SqlClient that is becoming unmanageable. About 4s from a minor edit to intellisense catching up.

What is happening when a change unrelated to SqlClient is made? Is the SQL still getting unnecessarily passed and new types created?

**Comment by smoothdeveloper** [comment] 2020-09-19 21:56
maybe related: https://github.com/dotnet/fsharp/pull/10159

**Comment by smoothdeveloper** [comment] 2020-11-20 11:58
Closing, we'd need more specific / reproducible description of the issue.

**Closed by smoothdeveloper** 2020-11-20 11:58 UTC
