### ISSUE TITLE
Columns returned from SqlServer graph queries are Option<T>

### ISSUE THREAD

**Issue by aVikingTrex** [fsprojects/FSharp.Data.SqlClient#346] opened 2019-06-18 11:26 UTC
### Description

Running into an issue where I have tables with columns that are NOT NULL that are returning as Option<T> when queried using MATCH ()

### Repro steps

Have a table that has columns all NOT NULL. Query using a SqlCommandProvider with [<Literal>] string that contains a WHERE MATCH clause 

### Expected behavior

Columns found in the query should not be nullable and be type T

### Actual behavior

Columns are found as Option<T>

**Comment by smoothdeveloper** [comment] 2019-06-18 12:43
@aVikingTrex thanks for reporting, this may be due to SQL Server limitation, but it would be easier to identify the root cause with a complete sample?

**Comment by smoothdeveloper** [comment] 2020-11-20 11:20
@aVikingTrex I'm closing this until we get more details on your end.

**Closed by smoothdeveloper** 2020-11-20 11:20 UTC
